### ISSUE TITLE
How to save the trained model

### ISSUE THREAD

**Issue by MatheusNtg** [helboukkouri/character-bert-pretraining#1]
I saw that there is no parameter to save the model after pre-train on the class `pretrain_model.py`, since, what is the proper way to save our pre-trained model?

**Comment by helboukkouri** [comment]
Hi @MatheusNtg, is this what you are looking for ? 
https://github.com/helboukkouri/character-bert-pretraining/blob/main/pretrain_model.py#L191-L197

**Comment by MatheusNtg** [comment]
These are the checkpoints for the training, isn't? Can I use these checkpoints on the method `from_pretrained`?

**Comment by helboukkouri** [comment]
Do you want to load a pre-trained model ? Or do you want to save the model after/during the pre-training ?

**Comment by MatheusNtg** [comment]
I want to load the final pre-trained model that I trained with the method `from_pretrained`

**Comment by helboukkouri** [comment]
For that, use the checkpoint file which was produced during pre-training (check [these lines](https://github.com/helboukkouri/character-bert-pretraining/blob/main/pretrain_model.py#L1207-L1215))

```python
import torch

ckpt_path = "./insert/your/path/here"
ckpt = torch.load(ckpt_path)
state_dict = ckpt["model"]

# Assuming the variable model has a valid BERT/CharacterBERT model
model  = model.load_state_dict(state_dict, map_location="cpu")
```

Depending on what you have in your `model` variable you may have some warning logs :)

**Comment by MatheusNtg** [comment]
Thanks 🙃

**Comment by MatheusNtg** [comment]
Can you tell me if this way I will load correctly the model that I trained?
The `path_for_the_config_file_specfied_on_the_readme` string is the string present on https://huggingface.co/helboukkouri/character-bert/resolve/main/config.json
```python
from transformers import (
    CharacterBertConfig, CharacterBertForPreTraining
)

model_config = CharacterBertConfig.from_pretrained('path_for_the_config_file_specfied_on_the_readme')

model = CharacterBertForPreTraining(model_config)

checkpoint = torch.load('path_for_ckpt')

model.load_state_dict(checkpoint['model'], strict=True)
```

**Comment by helboukkouri** [comment]
Hi @MatheusNtg. Since I am not sure what you are referring to when you say 'path_for_the_..' I will clarify just in case.

If you are using the PR code, which you seem to be doing since you are importing CharacterBERT classes from the `transformers` library, then the strings you need to input to load a pre-trained model/config/tokenizer are [the ones specified here.](https://github.com/helboukkouri/transformers/blob/add-character-bert/src/transformers/models/character_bert/modeling_character_bert.py#L69-L73) (e.g. "helboukkouri/character-bert")

About loading a pre-trained checkpoint, what you are doing seems to be correct. If you are paranoid as I sometimes am myself, you can make a copy of the original model before loading the checkpoint then load the checkpoint on another copy and compare the weights of both models using `model.parameters()` to check that the `load_state_dict` had an actual effect. You may also compare the loaded model with the weights in the checkpoint directly and check whether they match. 😊

**Comment by MatheusNtg** [comment]
Thanks for the answers, about the `path_for_the_config_file_specfied_on_the_readme` this is just the configuration file present on https://huggingface.co/helboukkouri/character-bert/resolve/main/config.json. I use this config file because the `CharacterBertConfig.from_pretrained` needs a configuration file to be instantiated. I think that the config file present [here ](https://huggingface.co/helboukkouri/character-bert/resolve/main/config.json) is the raw model without pre-training, right? If it is, then I can instantiate the model with that config file and then load the weights through `load_state_dict`. And sorry if I'm persevering in this subject but I need to understand this and be sure if I'm doing the right thing because I'm using this on a work that is intended to be published.

**Comment by MatheusNtg** [comment]
Hi @helboukkouri, thanks for the answers, I'm having difficulties to load the model from the checkpoint, I think that the part that I'm not doing right is when you say:
```python
# Assuming the variable model has a valid BERT/CharacterBERT model
```
Could you please show an example were there is a valid CharcterBERT model in the variable `model`? The code that I'm using trying to load the model from the checkpoint is this code:

```python
from transformers import CharacterBertModel

ckpt_path = 'path/to/mycheckpoint.pt'
state_dict = torch.load(ckpt_path)['model']

model = CharacterBertModel.from_pretrained('helboukkouri/character-bert')

model.load_state_dict(state_dict)
```

But this gives me the following errors:

```
ome weights of the model checkpoint at helboukkouri/character-bert were not used when initializing CharacterBertModel: ['cls.predictions.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing CharacterBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing CharacterBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Traceback (most recent call last):
  File "save_model.py", line 19, in <module>
    model.load_state_dict(state_dict)
  File "/home/matheus/anaconda3/envs/character-bert-pt-test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1406, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CharacterBertModel:
	Missing key(s) in state_dict: "embeddings.position_ids", "embeddings.word_embeddings._char_embedding_weights", "embeddings.word_embeddings.char_conv_0.weight", "embeddings.word_embeddings.char_conv_0.bias", "embeddings.word_embeddings.char_conv_1.weight", "embeddings.word_embeddings.char_conv_1.bias", "embeddings.word_embeddings.char_conv_2.weight", "embeddings.word_embeddings.char_conv_2.bias", "embeddings.word_embeddings.char_conv_3.weight", "embeddings.word_embeddings.char_conv_3.bias", "embeddings.word_embeddings.char_conv_4.weight", "embeddings.word_embeddings.char_conv_4.bias", "embeddings.word_embeddings.char_conv_5.weight", "embeddings.word_embeddings.char_conv_5.bias", "embeddings.word_embeddings.char_conv_6.weight", "embeddings.word_embeddings.char_conv_6.bias", "embeddings.word_embeddings._highways._layers.0.weight", "embeddings.word_embeddings._highways._layers.0.bias", "embeddings.word_embeddings._highways._layers.1.weight", "embeddings.word_embeddings._highways._layers.1.bias", "embeddings.word_embeddings._projection.weight", "embeddings.word_embeddings._projection.bias", "embeddings.position_embeddings.weight", "embeddings.token_type_embeddings.weight", "embeddings.LayerNorm.weight", "embeddings.LayerNorm.bias", "encoder.layer.0.attention.self.query.weight", "encoder.layer.0.attention.self.query.bias", "encoder.layer.0.attention.self.key.weight", "encoder.layer.0.attention.self.key.bias", "encoder.layer.0.attention.self.value.weight", "encoder.layer.0.attention.self.value.bias", "encoder.layer.0.attention.output.dense.weight", "encoder.layer.0.attention.output.dense.bias", "encoder.layer.0.attention.output.LayerNorm.weight", "encoder.layer.0.attention.output.LayerNorm.bias", "encoder.layer.0.intermediate.dense.weight", "encoder.layer.0.intermediate.dense.bias", "encoder.layer.0.output.dense.weight", "encoder.layer.0.output.dense.bias", "encoder.layer.0.output.LayerNorm.weight", "encoder.layer.0.output.LayerNorm.bias", "encoder.layer.1.attention.self.query.weight", "encoder.layer.1.attention.self.query.bias", "encoder.layer.1.attention.self.key.weight", "encoder.layer.1.attention.self.key.bias", "encoder.layer.1.attention.self.value.weight", "encoder.layer.1.attention.self.value.bias", "encoder.layer.1.attention.output.dense.weight", "encoder.layer.1.attention.output.dense.bias", "encoder.layer.1.attention.output.LayerNorm.weight", "encoder.layer.1.attention.output.LayerNorm.bias", "encoder.layer.1.intermediate.dense.weight", "encoder.layer.1.intermediate.dense.bias", "encoder.layer.1.output.dense.weight", "encoder.layer.1.output.dense.bias", "encoder.layer.1.output.LayerNorm.weight", "encoder.layer.1.output.LayerNorm.bias", "encoder.layer.2.attention.self.query.weight", "encoder.layer.2.attention.self.query.bias", "encoder.layer.2.attention.self.key.weight", "encoder.layer.2.attention.self.key.bias", "encoder.layer.2.attention.self.value.weight", "encoder.layer.2.attention.self.value.bias", "encoder.layer.2.attention.output.dense.weight", "encoder.layer.2.attention.output.dense.bias", "encoder.layer.2.attention.output.LayerNorm.weight", "encoder.layer.2.attention.output.LayerNorm.bias", "encoder.layer.2.intermediate.dense.weight", "encoder.layer.2.intermediate.dense.bias", "encoder.layer.2.output.dense.weight", "encoder.layer.2.output.dense.bias", "encoder.layer.2.output.LayerNorm.weight", "encoder.layer.2.output.LayerNorm.bias", "encoder.layer.3.attention.self.query.weight", "encoder.layer.3.attention.self.query.bias", "encoder.layer.3.attention.self.key.weight", "encoder.layer.3.attention.self.key.bias", "encoder.layer.3.attention.self.value.weight", "encoder.layer.3.attention.self.value.bias", "encoder.layer.3.attention.output.dense.weight", "encoder.layer.3.attention.output.dense.bias", "encoder.layer.3.attention.output.LayerNorm.weight", "encoder.layer.3.attention.output.LayerNorm.bias", "encoder.layer.3.intermediate.dense.weight", "encoder.layer.3.intermediate.dense.bias", "encoder.layer.3.output.dense.weight", "encoder.layer.3.output.dense.bias", "encoder.layer.3.output.LayerNorm.weight", "encoder.layer.3.output.LayerNorm.bias", "encoder.layer.4.attention.self.query.weight", "encoder.layer.4.attention.self.query.bias", "encoder.layer.4.attention.self.key.weight", "encoder.layer.4.attention.self.key.bias", "encoder.layer.4.attention.self.value.weight", "encoder.layer.4.attention.self.value.bias", "encoder.layer.4.attention.output.dense.weight", "encoder.layer.4.attention.output.dense.bias", "encoder.layer.4.attention.output.LayerNorm.weight", "encoder.layer.4.attention.output.LayerNorm.bias", "encoder.layer.4.intermediate.dense.weight", "encoder.layer.4.intermediate.dense.bias", "encoder.layer.4.output.dense.weight", "encoder.layer.4.output.dense.bias", "encoder.layer.4.output.LayerNorm.weight", "encoder.layer.4.output.LayerNorm.bias", "encoder.layer.5.attention.self.query.weight", "encoder.layer.5.attention.self.query.bias", "encoder.layer.5.attention.self.key.weight", "encoder.layer.5.attention.self.key.bias", "encoder.layer.5.attention.self.value.weight", "encoder.layer.5.attention.self.value.bias", "encoder.layer.5.attention.output.dense.weight", "encoder.layer.5.attention.output.dense.bias", "encoder.layer.5.attention.output.LayerNorm.weight", "encoder.layer.5.attention.output.LayerNorm.bias", "encoder.layer.5.intermediate.dense.weight", "encoder.layer.5.intermediate.dense.bias", "encoder.layer.5.output.dense.weight", "encoder.layer.5.output.dense.bias", "encoder.layer.5.output.LayerNorm.weight", "encoder.layer.5.output.LayerNorm.bias", "encoder.layer.6.attention.self.query.weight", "encoder.layer.6.attention.self.query.bias", "encoder.layer.6.attention.self.key.weight", "encoder.layer.6.attention.self.key.bias", "encoder.layer.6.attention.self.value.weight", "encoder.layer.6.attention.self.value.bias", "encoder.layer.6.attention.output.dense.weight", "encoder.layer.6.attention.output.dense.bias", "encoder.layer.6.attention.output.LayerNorm.weight", "encoder.layer.6.attention.output.LayerNorm.bias", "encoder.layer.6.intermediate.dense.weight", "encoder.layer.6.intermediate.dense.bias", "encoder.layer.6.output.dense.weight", "encoder.layer.6.output.dense.bias", "encoder.layer.6.output.LayerNorm.weight", "encoder.layer.6.output.LayerNorm.bias", "encoder.layer.7.attention.self.query.weight", "encoder.layer.7.attention.self.query.bias", "encoder.layer.7.attention.self.key.weight", "encoder.layer.7.attention.self.key.bias", "encoder.layer.7.attention.self.value.weight", "encoder.layer.7.attention.self.value.bias", "encoder.layer.7.attention.output.dense.weight", "encoder.layer.7.attention.output.dense.bias", "encoder.layer.7.attention.output.LayerNorm.weight", "encoder.layer.7.attention.output.LayerNorm.bias", "encoder.layer.7.intermediate.dense.weight", "encoder.layer.7.intermediate.dense.bias", "encoder.layer.7.output.dense.weight", "encoder.layer.7.output.dense.bias", "encoder.layer.7.output.LayerNorm.weight", "encoder.layer.7.output.LayerNorm.bias", "encoder.layer.8.attention.self.query.weight", "encoder.layer.8.attention.self.query.bias", "encoder.layer.8.attention.self.key.weight", "encoder.layer.8.attention.self.key.bias", "encoder.layer.8.attention.self.value.weight", "encoder.layer.8.attention.self.value.bias", "encoder.layer.8.attention.output.dense.weight", "encoder.layer.8.attention.output.dense.bias", "encoder.layer.8.attention.output.LayerNorm.weight", "encoder.layer.8.attention.output.LayerNorm.bias", "encoder.layer.8.intermediate.dense.weight", "encoder.layer.8.intermediate.dense.bias", "encoder.layer.8.output.dense.weight", "encoder.layer.8.output.dense.bias", "encoder.layer.8.output.LayerNorm.weight", "encoder.layer.8.output.LayerNorm.bias", "encoder.layer.9.attention.self.query.weight", "encoder.layer.9.attention.self.query.bias", "encoder.layer.9.attention.self.key.weight", "encoder.layer.9.attention.self.key.bias", "encoder.layer.9.attention.self.value.weight", "encoder.layer.9.attention.self.value.bias", "encoder.layer.9.attention.output.dense.weight", "encoder.layer.9.attention.output.dense.bias", "encoder.layer.9.attention.output.LayerNorm.weight", "encoder.layer.9.attention.output.LayerNorm.bias", "encoder.layer.9.intermediate.dense.weight", "encoder.layer.9.intermediate.dense.bias", "encoder.layer.9.output.dense.weight", "encoder.layer.9.output.dense.bias", "encoder.layer.9.output.LayerNorm.weight", "encoder.layer.9.output.LayerNorm.bias", "encoder.layer.10.attention.self.query.weight", "encoder.layer.10.attention.self.query.bias", "encoder.layer.10.attention.self.key.weight", "encoder.layer.10.attention.self.key.bias", "encoder.layer.10.attention.self.value.weight", "encoder.layer.10.attention.self.value.bias", "encoder.layer.10.attention.output.dense.weight", "encoder.layer.10.attention.output.dense.bias", "encoder.layer.10.attention.output.LayerNorm.weight", "encoder.layer.10.attention.output.LayerNorm.bias", "encoder.layer.10.intermediate.dense.weight", "encoder.layer.10.intermediate.dense.bias", "encoder.layer.10.output.dense.weight", "encoder.layer.10.output.dense.bias", "encoder.layer.10.output.LayerNorm.weight", "encoder.layer.10.output.LayerNorm.bias", "encoder.layer.11.attention.self.query.weight", "encoder.layer.11.attention.self.query.bias", "encoder.layer.11.attention.self.key.weight", "encoder.layer.11.attention.self.key.bias", "encoder.layer.11.attention.self.value.weight", "encoder.layer.11.attention.self.value.bias", "encoder.layer.11.attention.output.dense.weight", "encoder.layer.11.attention.output.dense.bias", "encoder.layer.11.attention.output.LayerNorm.weight", "encoder.layer.11.attention.output.LayerNorm.bias", "encoder.layer.11.intermediate.dense.weight", "encoder.layer.11.intermediate.dense.bias", "encoder.layer.11.output.dense.weight", "encoder.layer.11.output.dense.bias", "encoder.layer.11.output.LayerNorm.weight", "encoder.layer.11.output.LayerNorm.bias", "pooler.dense.weight", "pooler.dense.bias". 
	Unexpected key(s) in state_dict: "character_bert.embeddings.position_ids", "character_bert.embeddings.word_embeddings._char_embedding_weights", "character_bert.embeddings.word_embeddings.char_conv_0.weight", "character_bert.embeddings.word_embeddings.char_conv_0.bias", "character_bert.embeddings.word_embeddings.char_conv_1.weight", "character_bert.embeddings.word_embeddings.char_conv_1.bias", "character_bert.embeddings.word_embeddings.char_conv_2.weight", "character_bert.embeddings.word_embeddings.char_conv_2.bias", "character_bert.embeddings.word_embeddings.char_conv_3.weight", "character_bert.embeddings.word_embeddings.char_conv_3.bias", "character_bert.embeddings.word_embeddings.char_conv_4.weight", "character_bert.embeddings.word_embeddings.char_conv_4.bias", "character_bert.embeddings.word_embeddings.char_conv_5.weight", "character_bert.embeddings.word_embeddings.char_conv_5.bias", "character_bert.embeddings.word_embeddings.char_conv_6.weight", "character_bert.embeddings.word_embeddings.char_conv_6.bias", "character_bert.embeddings.word_embeddings._highways._layers.0.weight", "character_bert.embeddings.word_embeddings._highways._layers.0.bias", "character_bert.embeddings.word_embeddings._highways._layers.1.weight", "character_bert.embeddings.word_embeddings._highways._layers.1.bias", "character_bert.embeddings.word_embeddings._projection.weight", "character_bert.embeddings.word_embeddings._projection.bias", "character_bert.embeddings.position_embeddings.weight", "character_bert.embeddings.token_type_embeddings.weight", "character_bert.embeddings.LayerNorm.weight", "character_bert.embeddings.LayerNorm.bias", "character_bert.encoder.layer.0.attention.self.query.weight", "character_bert.encoder.layer.0.attention.self.query.bias", "character_bert.encoder.layer.0.attention.self.key.weight", "character_bert.encoder.layer.0.attention.self.key.bias", "character_bert.encoder.layer.0.attention.self.value.weight", "character_bert.encoder.layer.0.attention.self.value.bias", "character_bert.encoder.layer.0.attention.output.dense.weight", "character_bert.encoder.layer.0.attention.output.dense.bias", "character_bert.encoder.layer.0.attention.output.LayerNorm.weight", "character_bert.encoder.layer.0.attention.output.LayerNorm.bias", "character_bert.encoder.layer.0.intermediate.dense.weight", "character_bert.encoder.layer.0.intermediate.dense.bias", "character_bert.encoder.layer.0.output.dense.weight", "character_bert.encoder.layer.0.output.dense.bias", "character_bert.encoder.layer.0.output.LayerNorm.weight", "character_bert.encoder.layer.0.output.LayerNorm.bias", "character_bert.encoder.layer.1.attention.self.query.weight", "character_bert.encoder.layer.1.attention.self.query.bias", "character_bert.encoder.layer.1.attention.self.key.weight", "character_bert.encoder.layer.1.attention.self.key.bias", "character_bert.encoder.layer.1.attention.self.value.weight", "character_bert.encoder.layer.1.attention.self.value.bias", "character_bert.encoder.layer.1.attention.output.dense.weight", "character_bert.encoder.layer.1.attention.output.dense.bias", "character_bert.encoder.layer.1.attention.output.LayerNorm.weight", "character_bert.encoder.layer.1.attention.output.LayerNorm.bias", "character_bert.encoder.layer.1.intermediate.dense.weight", "character_bert.encoder.layer.1.intermediate.dense.bias", "character_bert.encoder.layer.1.output.dense.weight", "character_bert.encoder.layer.1.output.dense.bias", "character_bert.encoder.layer.1.output.LayerNorm.weight", "character_bert.encoder.layer.1.output.LayerNorm.bias", "character_bert.encoder.layer.2.attention.self.query.weight", "character_bert.encoder.layer.2.attention.self.query.bias", "character_bert.encoder.layer.2.attention.self.key.weight", "character_bert.encoder.layer.2.attention.self.key.bias", "character_bert.encoder.layer.2.attention.self.value.weight", "character_bert.encoder.layer.2.attention.self.value.bias", "character_bert.encoder.layer.2.attention.output.dense.weight", "character_bert.encoder.layer.2.attention.output.dense.bias", "character_bert.encoder.layer.2.attention.output.LayerNorm.weight", "character_bert.encoder.layer.2.attention.output.LayerNorm.bias", "character_bert.encoder.layer.2.intermediate.dense.weight", "character_bert.encoder.layer.2.intermediate.dense.bias", "character_bert.encoder.layer.2.output.dense.weight", "character_bert.encoder.layer.2.output.dense.bias", "character_bert.encoder.layer.2.output.LayerNorm.weight", "character_bert.encoder.layer.2.output.LayerNorm.bias", "character_bert.encoder.layer.3.attention.self.query.weight", "character_bert.encoder.layer.3.attention.self.query.bias", "character_bert.encoder.layer.3.attention.self.key.weight", "character_bert.encoder.layer.3.attention.self.key.bias", "character_bert.encoder.layer.3.attention.self.value.weight", "character_bert.encoder.layer.3.attention.self.value.bias", "character_bert.encoder.layer.3.attention.output.dense.weight", "character_bert.encoder.layer.3.attention.output.dense.bias", "character_bert.encoder.layer.3.attention.output.LayerNorm.weight", "character_bert.encoder.layer.3.attention.output.LayerNorm.bias", "character_bert.encoder.layer.3.intermediate.dense.weight", "character_bert.encoder.layer.3.intermediate.dense.bias", "character_bert.encoder.layer.3.output.dense.weight", "character_bert.encoder.layer.3.output.dense.bias", "character_bert.encoder.layer.3.output.LayerNorm.weight", "character_bert.encoder.layer.3.output.LayerNorm.bias", "character_bert.encoder.layer.4.attention.self.query.weight", "character_bert.encoder.layer.4.attention.self.query.bias", "character_bert.encoder.layer.4.attention.self.key.weight", "character_bert.encoder.layer.4.attention.self.key.bias", "character_bert.encoder.layer.4.attention.self.value.weight", "character_bert.encoder.layer.4.attention.self.value.bias", "character_bert.encoder.layer.4.attention.output.dense.weight", "character_bert.encoder.layer.4.attention.output.dense.bias", "character_bert.encoder.layer.4.attention.output.LayerNorm.weight", "character_bert.encoder.layer.4.attention.output.LayerNorm.bias", "character_bert.encoder.layer.4.intermediate.dense.weight", "character_bert.encoder.layer.4.intermediate.dense.bias", "character_bert.encoder.layer.4.output.dense.weight", "character_bert.encoder.layer.4.output.dense.bias", "character_bert.encoder.layer.4.output.LayerNorm.weight", "character_bert.encoder.layer.4.output.LayerNorm.bias", "character_bert.encoder.layer.5.attention.self.query.weight", "character_bert.encoder.layer.5.attention.self.query.bias", "character_bert.encoder.layer.5.attention.self.key.weight", "character_bert.encoder.layer.5.attention.self.key.bias", "character_bert.encoder.layer.5.attention.self.value.weight", "character_bert.encoder.layer.5.attention.self.value.bias", "character_bert.encoder.layer.5.attention.output.dense.weight", "character_bert.encoder.layer.5.attention.output.dense.bias", "character_bert.encoder.layer.5.attention.output.LayerNorm.weight", "character_bert.encoder.layer.5.attention.output.LayerNorm.bias", "character_bert.encoder.layer.5.intermediate.dense.weight", "character_bert.encoder.layer.5.intermediate.dense.bias", "character_bert.encoder.layer.5.output.dense.weight", "character_bert.encoder.layer.5.output.dense.bias", "character_bert.encoder.layer.5.output.LayerNorm.weight", "character_bert.encoder.layer.5.output.LayerNorm.bias", "character_bert.encoder.layer.6.attention.self.query.weight", "character_bert.encoder.layer.6.attention.self.query.bias", "character_bert.encoder.layer.6.attention.self.key.weight", "character_bert.encoder.layer.6.attention.self.key.bias", "character_bert.encoder.layer.6.attention.self.value.weight", "character_bert.encoder.layer.6.attention.self.value.bias", "character_bert.encoder.layer.6.attention.output.dense.weight", "character_bert.encoder.layer.6.attention.output.dense.bias", "character_bert.encoder.layer.6.attention.output.LayerNorm.weight", "character_bert.encoder.layer.6.attention.output.LayerNorm.bias", "character_bert.encoder.layer.6.intermediate.dense.weight", "character_bert.encoder.layer.6.intermediate.dense.bias", "character_bert.encoder.layer.6.output.dense.weight", "character_bert.encoder.layer.6.output.dense.bias", "character_bert.encoder.layer.6.output.LayerNorm.weight", "character_bert.encoder.layer.6.output.LayerNorm.bias", "character_bert.encoder.layer.7.attention.self.query.weight", "character_bert.encoder.layer.7.attention.self.query.bias", "character_bert.encoder.layer.7.attention.self.key.weight", "character_bert.encoder.layer.7.attention.self.key.bias", "character_bert.encoder.layer.7.attention.self.value.weight", "character_bert.encoder.layer.7.attention.self.value.bias", "character_bert.encoder.layer.7.attention.output.dense.weight", "character_bert.encoder.layer.7.attention.output.dense.bias", "character_bert.encoder.layer.7.attention.output.LayerNorm.weight", "character_bert.encoder.layer.7.attention.output.LayerNorm.bias", "character_bert.encoder.layer.7.intermediate.dense.weight", "character_bert.encoder.layer.7.intermediate.dense.bias", "character_bert.encoder.layer.7.output.dense.weight", "character_bert.encoder.layer.7.output.dense.bias", "character_bert.encoder.layer.7.output.LayerNorm.weight", "character_bert.encoder.layer.7.output.LayerNorm.bias", "character_bert.encoder.layer.8.attention.self.query.weight", "character_bert.encoder.layer.8.attention.self.query.bias", "character_bert.encoder.layer.8.attention.self.key.weight", "character_bert.encoder.layer.8.attention.self.key.bias", "character_bert.encoder.layer.8.attention.self.value.weight", "character_bert.encoder.layer.8.attention.self.value.bias", "character_bert.encoder.layer.8.attention.output.dense.weight", "character_bert.encoder.layer.8.attention.output.dense.bias", "character_bert.encoder.layer.8.attention.output.LayerNorm.weight", "character_bert.encoder.layer.8.attention.output.LayerNorm.bias", "character_bert.encoder.layer.8.intermediate.dense.weight", "character_bert.encoder.layer.8.intermediate.dense.bias", "character_bert.encoder.layer.8.output.dense.weight", "character_bert.encoder.layer.8.output.dense.bias", "character_bert.encoder.layer.8.output.LayerNorm.weight", "character_bert.encoder.layer.8.output.LayerNorm.bias", "character_bert.encoder.layer.9.attention.self.query.weight", "character_bert.encoder.layer.9.attention.self.query.bias", "character_bert.encoder.layer.9.attention.self.key.weight", "character_bert.encoder.layer.9.attention.self.key.bias", "character_bert.encoder.layer.9.attention.self.value.weight", "character_bert.encoder.layer.9.attention.self.value.bias", "character_bert.encoder.layer.9.attention.output.dense.weight", "character_bert.encoder.layer.9.attention.output.dense.bias", "character_bert.encoder.layer.9.attention.output.LayerNorm.weight", "character_bert.encoder.layer.9.attention.output.LayerNorm.bias", "character_bert.encoder.layer.9.intermediate.dense.weight", "character_bert.encoder.layer.9.intermediate.dense.bias", "character_bert.encoder.layer.9.output.dense.weight", "character_bert.encoder.layer.9.output.dense.bias", "character_bert.encoder.layer.9.output.LayerNorm.weight", "character_bert.encoder.layer.9.output.LayerNorm.bias", "character_bert.encoder.layer.10.attention.self.query.weight", "character_bert.encoder.layer.10.attention.self.query.bias", "character_bert.encoder.layer.10.attention.self.key.weight", "character_bert.encoder.layer.10.attention.self.key.bias", "character_bert.encoder.layer.10.attention.self.value.weight", "character_bert.encoder.layer.10.attention.self.value.bias", "character_bert.encoder.layer.10.attention.output.dense.weight", "character_bert.encoder.layer.10.attention.output.dense.bias", "character_bert.encoder.layer.10.attention.output.LayerNorm.weight", "character_bert.encoder.layer.10.attention.output.LayerNorm.bias", "character_bert.encoder.layer.10.intermediate.dense.weight", "character_bert.encoder.layer.10.intermediate.dense.bias", "character_bert.encoder.layer.10.output.dense.weight", "character_bert.encoder.layer.10.output.dense.bias", "character_bert.encoder.layer.10.output.LayerNorm.weight", "character_bert.encoder.layer.10.output.LayerNorm.bias", "character_bert.encoder.layer.11.attention.self.query.weight", "character_bert.encoder.layer.11.attention.self.query.bias", "character_bert.encoder.layer.11.attention.self.key.weight", "character_bert.encoder.layer.11.attention.self.key.bias", "character_bert.encoder.layer.11.attention.self.value.weight", "character_bert.encoder.layer.11.attention.self.value.bias", "character_bert.encoder.layer.11.attention.output.dense.weight", "character_bert.encoder.layer.11.attention.output.dense.bias", "character_bert.encoder.layer.11.attention.output.LayerNorm.weight", "character_bert.encoder.layer.11.attention.output.LayerNorm.bias", "character_bert.encoder.layer.11.intermediate.dense.weight", "character_bert.encoder.layer.11.intermediate.dense.bias", "character_bert.encoder.layer.11.output.dense.weight", "character_bert.encoder.layer.11.output.dense.bias", "character_bert.encoder.layer.11.output.LayerNorm.weight", "character_bert.encoder.layer.11.output.LayerNorm.bias", "character_bert.pooler.dense.weight", "character_bert.pooler.dense.bias", "cls.predictions.bias", "cls.predictions.transform.dense.weight", "cls.predictions.transform.dense.bias", "cls.predictions.transform.LayerNorm.weight", "cls.predictions.transform.LayerNorm.bias", "cls.predictions.decoder.weight", "cls.predictions.decoder.bias", "cls.seq_relationship.weight", "cls.seq_relationship.bias".
```

Because of these errors I can't use the model. It seems that the my checkpoint has a different architeture from the model that you offer on HuggingFace, these should not be the case once that I trained the model using your instructions, right?

And the only way that I can run (and load the weights) is if I use the following code:
```python
from transformers import CharacterBertModel, CharacterBertForPreTraining

ckpt_path = 'path/to/mycheckpoint.pt'
state_dict = torch.load(ckpt_path)['model']

model = CharacterBertForPreTraining.from_pretrained('helboukkouri/character-bert')

model.load_state_dict(state_dict)
```

But with this I have a model for pre-training, right? Can this model be used in all tasks normally or it should be used only for training the model?

**Comment by helboukkouri** [comment]
Hi @MatheusNtg, the issues you're having are normal. The weights in the checkpoint come from a pre-training model so in order to load them back you need to do that using the same type of model -> a pre-training model.

There are many ways you could achieve what you're trying to do

- One way is to load the weights in `CharacterBertForPreTraining` then do `model = model.character_bert` which would effectively replace the pre-training model with the encoder part and drop the pre-training heads.
- Another way is to manually change the state dictionary by removing the pre-training head weights (those which keys start with `cls.`) and change the keys of the other weights by removing the `character_bert.` prefix. If you do this you can re-save this new state dict so that you can re-use it later and directly do `load_state_dict` on `CharacterBertModel`.

One last thing to keep in mind is that the `transformers` library version between the original CharacterBERT code and the PR code is not the same. So you may sometimes have some model "parts" that changed name so you'll need to rename them so that they match.

Sorry for all the trouble but this is still a WIP. When everything is merged I'll update the README.

**Comment by MatheusNtg** [comment]
@helboukkouri thanks for the answers, I will adapt my code to use your first suggestion.
